config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  
  resources :sale_on_sales do
    collection do
      get "all"
    end
  end
  resources :sale_on_sale_imports
end

app/models/sale_on_sale_import.rb
class SaleOnSaleImport < ActiveRecord::Base
  belongs_to :user
  validates :attachment, :presence => true
  has_attached_file :attachment, :s3_credentials => "#{RAILS_ROOT}/config/s3.yml", :path => "sale_on_sale_imports/attachments/:id/:style/:basename.:extension", :url => "/assets/sale_on_sale_import/:id/:style/:basename.:extension",	:storage => :s3
  
  delegate :upload, :to => :upload_handler

  def upload_handler
    SaleOnSaleImportHandler.new(self)
  end
  
end

app/controllers/sale_on_sale_imports_controller.rb
class SaleOnSaleImportsController < ApplicationController

  before_filter :authenticate_user_role
  layout "sale_on_sale"
  
  def authenticate_user_role
    redirect_to root_path if (current_user.nil? ? true : !current_user.roles.map(&:name).include?("cs"))
  end

  # GET /sale_on_sale_imports
  # GET /sale_on_sale_imports.xml
  def index
    @sale_on_sale_import = SaleOnSaleImport.new
    @sale_on_sale_imports = SaleOnSaleImport.all.reverse.paginate(:page => params[:page], :per_page => 50)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sale_on_sale_imports }
    end
  end

  # GET /sale_on_sale_imports/1
  # GET /sale_on_sale_imports/1.xml
  # def show
  #   @sale_on_sale_import = SaleOnSaleImport.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.xml  { render :xml => @sale_on_sale_import }
  #   end
  # end

  # GET /sale_on_sale_imports/new
  # GET /sale_on_sale_imports/new.xml
  def new
    @sale_on_sale_import = SaleOnSaleImport.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sale_on_sale_import }
    end
  end

  # GET /sale_on_sale_imports/1/edit
  def edit
    @sale_on_sale_import = SaleOnSaleImport.find(params[:id])
  end

  # POST /sale_on_sale_imports
  # POST /sale_on_sale_imports.xml
  def create
    params[:sale_on_sale_import][:user_id] = current_user.id
    @sale_on_sale_import = SaleOnSaleImport.new(params[:sale_on_sale_import])

    respond_to do |format|
      if @sale_on_sale_import.save
        @sale_on_sale_import.upload
        format.html { redirect_to(:back, :notice => 'Sale on sale import was successfully created.') }
        format.xml  { render :xml => @sale_on_sale_import, :status => :created, :location => @sale_on_sale_import }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sale_on_sale_import.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sale_on_sale_imports/1
  # PUT /sale_on_sale_imports/1.xml
  def update
    params[:sale_on_sale_import][:user_id] = current_user.id
    @sale_on_sale_import = SaleOnSaleImport.find(params[:id])

    respond_to do |format|
      if @sale_on_sale_import.update_attributes(params[:sale_on_sale_import])
        format.html { redirect_to(:back, :notice => 'Sale on sale import was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sale_on_sale_import.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_on_sale_imports/1
  # DELETE /sale_on_sale_imports/1.xml
  def destroy
    @sale_on_sale_import = SaleOnSaleImport.find(params[:id])
    @sale_on_sale_import.destroy

    respond_to do |format|
      format.html { redirect_to(sale_on_sale_imports_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/sale_on_sale_imports/_form.html.erb
<%= form_for @sale_on_sale_import, :html => {:multipart => true, :class => "well form-search"} do |file| %>
  <%= file.file_field :attachment %>
  <%= submit_tag("Upload", :class => "btn") %>
<% end %>

app/views/sale_on_sale_imports/_new_sale_on_sale.html.erb
<div class="well form-search">
  <%= link_to "Add Single Product", new_sale_on_sale_path , :class => "btn btn-primary" %></td>
</div>

app/views/sale_on_sale_imports/edit.html.erb
<h1>Editing Sale on Sale Import</h1>

<%= link_to 'Back', sale_on_sale_imports_path %>

app/views/sale_on_sale_imports/index.html.erb
<h1>Listing Sale on Sale Imports</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>File Name</th>
      <th>Uploaded by</th>
      <th>Uploaded at</th>
      <th>Download</th>
    </tr>
  </thead>
  <tbody>
    <% @sale_on_sale_imports.each do |sale_on_sale_import| %>
      <tr>
        <td><%= sale_on_sale_import.attachment_file_name %></td>
        <td><%= sale_on_sale_import.user.firstname %></td>
        <td><%= sale_on_sale_import.created_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
        <td><%= link_to 'Download', sale_on_sale_import.attachment.url, :class => "btn" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= will_paginate @sale_on_sale_imports %>

app/views/sale_on_sale_imports/new.html.erb
<h1>New Sale on Sale Import</h1>

<%= render  "new_sale_on_sale" %>

<%= link_to 'Back', sale_on_sale_imports_path %>