config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  
  resources :sale_on_sales do
    collection do
      get "all"
    end
  end
  resources :sale_on_sale_imports
end

app/models/sale_on_sale.rb
class SaleOnSale < ActiveRecord::Base
  has_one :product
  validates :amount, :presence => true, :numericality => true
  scope :active, where("starts_at < :start_time AND expires_at > :end_time", {:start_time => Time.now, :end_time => Time.now})
  
  def gen_code
    rand(9999).to_s+"SOS"+rand(9999).to_s
  end

  def is_active?
    (starts_at < Time.now && expires_at > Time.now)
  end
end

app/controllers/sale_on_sales_controller.rb
class SaleOnSalesController < ApplicationController
  before_filter :authenticate_user_role
  before_filter :sale_import
  layout "sale_on_sale"
  
  def authenticate_user_role
    redirect_to root_path if (current_user.nil? ? true : !current_user.roles.map(&:name).include?("cs"))
  end

  def index
    @sale_on_sales = SaleOnSale.includes(:product).active.reverse.paginate(:page => params[:page], :per_page => 50)
    respond_to do |format|
      format.html
      format.xml
    end
  end

  def all
    @sale_on_sales = SaleOnSale.includes(:product).all.reverse.paginate(:page => params[:page], :per_page => 50)
    respond_to do |format|
      format.html
      format.xml
    end
  end
  
  def show
    @product = Product.find_by_permalink(params[:id])
    respond_to do |format|
      format.html
      format.xml
    end
  end
  
  def edit
    @product = Product.find_by_permalink(params[:id])
    respond_to do |format|
      format.html
      format.xml
    end
  end

  def update
    product = Product.find_by_permalink(params[:id])
    respond_to do |format|
      if product.update_attributes(params[:product])
        sale_on_sale = SaleOnSale.find(product.sale_on_sale_id)
        sale_on_sale.update_attributes(:amount => (product.price-product.on_sale_amount))
        format.html { redirect_to :back, :notice => "#{product.name}'s promoted amount has been updated successfully!" }
        format.xml
      else
        format.html { redirect_to :back, :alert => "#{product.name}'s promoted amount couldn't be updated. Here is the error: #{product.errors}" }
      end
    end
  end

  def destroy
   product=Product.find_by_permalink(params[:id])
   respond_to do |format|
      @sos=SaleOnSale.find(product.sale_on_sale_id)
      if @sos.destroy
      product.update_attributes(:is_sos => false , :sale_on_sale_id => nil , :on_sale_amount => nil)
      puts "Inside:: #{@sos}"
      format.html { redirect_to :back, :notice => "#{product.name}'s promoted amount has been deleted successfully!" }
      format.xml
     else
      format.html { redirect_to :back, :alert => "#{product.name}'s promoted SOS couldn't be updated. Here is the error: #{product.errors}" }
     end    
    end
  end

  def new
    @sale_on_sale = SaleOnSale.new
  end

  def create
    promoted_amount = BigDecimal.new(params[:sale_on_sale][:amount])
    product = Variant.where(:sku => params[:sku]).first.try(:product)
    if product.nil?
      redirect_to sale_on_sales_path , :notice => "Product Not Found!!!!!!"
    else
      start_date = "#{params[:sale_on_sale]["starts_at(3i)"]}/#{params[:sale_on_sale]["starts_at(2i)"]}/#{params[:sale_on_sale]["starts_at(1i)"]} #{params[:sale_on_sale]["starts_at(4i)"]}:#{params[:sale_on_sale]["starts_at(5i)"]}:00"
      end_date = "#{params[:sale_on_sale]["expires_at(3i)"]}/#{params[:sale_on_sale]["expires_at(2i)"]}/#{params[:sale_on_sale]["expires_at(1i)"]} #{params[:sale_on_sale]["expires_at(4i)"]}:#{params[:sale_on_sale]["expires_at(5i)"]}:00"
      start_date = DateTime.strptime("#{start_date}","%d/%m/%Y %H:%M:%S")
      puts start_date
      end_date = DateTime.strptime("#{end_date}","%d/%m/%Y %H:%M:%S")

      sale_on_sale = SaleOnSale.new(:name => "Sale On Sale", :description => "Sale on Sale..", :amount => (product.price-promoted_amount), :starts_at => start_date, :expires_at => end_date)
      sale_on_sale.code = sale_on_sale.gen_code
      sale_on_sale.amount = (product.price-promoted_amount)
      sale_on_sale.save
      product.update_attributes(:is_sos => true, :sale_on_sale_id => sale_on_sale.id, :on_sale_amount => promoted_amount)
      redirect_to sale_on_sales_path , :notice => "New SaleOnSale data created" 
    end
  end

  def sale_import
    @sale_on_sale_import = SaleOnSaleImport.new
  end
end

app/views/sale_on_sales/_sale_on_sale_promotions.html.erb
<table class="table striped">
  <thead>
    <tr>
      <th>Product's Name</th>
      <th>Product's price</th>
      <th>Product's discounted price</th>
      <th>Promoted Price</th>
      <th>Promotion Code</th>
      <th>Promotion Amount</th>
      <th>Started at</th>
      <th>Expire at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @sale_on_sales.each do |sale_on_sale| %>
      <tr>
        <% product = sale_on_sale.product %>
        <% unless product.nil? %>
          <td><%= link_to product.name, sale_on_sale_path(product.permalink) %></td>
          <td><%= product.cost_price %></td>
          <td><%= product.price %></td>
          <td>
            <%= form_for product, :url => sale_on_sale_path(product.permalink) do |f| %>
              <%= f.text_field :on_sale_amount, :class => "span1" %>
            <% end %>
          </td>
          <td><%= product.promotion_code %></td>
          <td><%= product.promotioned_amount %></td>
          <td><%= product.sale_on_sale.starts_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
          <td><%= product.sale_on_sale.expires_at.strftime("%d/%m/%Y %H:%M:%S") %></td>
          <td><%= link_to "Edit", edit_sale_on_sale_path(product.permalink), :class => "btn btn-mini btn-primary" %> <%#= link_to t('.destroy', :default => t("helpers.links.destroy")), sale_on_sale_path(product.permalink), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'  %>  
            <td><%= link_to "Show", sale_on_sale_path(product.permalink), :method => :destroy, :class => "btn btn-mini btn-primary" %></td>
          <td><%= button_to "Delete", sale_on_sale_path(product.permalink), :method => 'delete' , :class => "btn btn-mini btn-danger"%> </td>

          </td>
        <% end %>
      <tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @sale_on_sales %>

app/views/sale_on_sales/all.html.erb
<%= render "sale_promotion_menu" %>

<%= render "sale_on_sale_promotions" %>

app/views/sale_on_sales/edit.html.erb
<%= form_for @product, :url => sale_on_sale_path(@product.permalink), :html => {:class => "form-horizontal"} do |f| %>
	<fieldset>
    <legend>Sale Promotion</legend>
    <div class="control-group">
      <label class="control-label">Product's Name:</label>
      <div class="controls">
        <%= @product.name %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Price:</label>
      <div class="controls">
        <%= @product.cost_price %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Discounted Price:</label>
      <div class="controls">
        <%= @product.price %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Promoted Price:</label>
      <div class="controls">
        <%= f.text_field :on_sale_amount %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Promotion Amount:</label>
      <div class="controls">
        <%= @product.promotioned_amount %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Promotion Code:</label>
      <div class="controls">
        <%= @product.promotion_code %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Promotion Code usage:</label>
      <div class="controls">
        <%= @product.try(:on_hand) %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit("Update", :class => "btn btn-warning") %>
      <%= link_to "Back", sale_on_sales_path, :class => "btn btn-primary" %>
    </div>
	 </fieldset>
<% end %>

app/views/sale_on_sales/index.html.erb
<%= render "sale_promotion_menu" %>
<%= render "sale_on_sale_promotions" %>

<script type="text/javascript">
	// function showUpdateButton(permalink){
	// 	$("#"+permalink).attr("disabled", "disabled");
	// 	if (permalink == "") {
	// 		alert("Sale Category's name can not be blank.");
	// 	}
	// 	else {
	// 		$.ajax({
	// 		    type: "POST",
	// 		    dataType: "json",
	// 		    url: "/sale_promotions"+permalink,
	// 		    data: {
	// 		    	"product": 
	// 		    	{
	// 		    		"name": permalink
	// 		    	}
	// 	    	},
	// 		   success: function(data){
	// 			 jQuery('.sale_category_id').append('<option value="'+data.id+'">'+data.name+'</option>');
	// 			 jQuery('.sale_category_id').val(data.id);
	// 			 //alert("DATA FROM SERVER: "+data.name);
	// 		    // here is where you process the return value from your controller method
	// 	        // the data variable will hold the return value if the call is successful
	// 	        // you can make your controller return the html to be inserted in your table
	// 	        // and insert it from here or just return a status message and build and add
	// 	        // the html manually here.
	//            },
	//            error: function(x){
	//              alert('There was a problem with the server. Please try again later');
	//            }
	// 		});
	// 	}
	// 	$(".create_sale_category_input").removeAttr("disabled");
	// 	removeNewSaleCategory();
	// 	return 0;
	// }
</script>

app/views/sale_on_sales/new.html.erb
<h1>New Sale on Sale Import</h1>
<% form_for @sale_on_sale do |form| %>
   <%= text_field_tag "sku", nil, :placeholder=> "SKU" %><br/>
   <%= form.text_field :amount , :placeholder=> "Promotion Amount" %><br/>
   <%= form.datetime_select :starts_at, {:order => [:day, :month, :year], :ampm => true}, { :class => "span1"}  %><br/>
   <%= form.datetime_select :expires_at, {:order => [:day, :month, :year], :ampm => true}, { :class => "span1"} %><br/>
   <%= form.submit(:class => "btn btn-primary") %>
   <% end %>
<%= link_to 'Back', sale_on_sales_path %>

app/views/sale_on_sales/show.html.erb
<div class="form-horizontal">
	<fieldset>
    <legend>Sale Promotion</legend>
    <div class="control-group">
      <label class="control-label">Product's Name:</label>
      <div class="controls">
        <%= @product.name %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Price:</label>
      <div class="controls">
        <%= @product.cost_price %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Discounted Price:</label>
      <div class="controls">
        <%= @product.price %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Promoted Price:</label>
      <div class="controls">
        <%= @product.on_sale_amount %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Promotion Amount:</label>
      <div class="controls">
        <%= @product.promotioned_amount %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Product's Promotion Code:</label>
      <div class="controls">
        <%= @product.promotion_code %>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label">Promotion Code usage:</label>
      <div class="controls">
        <%= @product.try(:on_hand) %>
      </div>
    </div>
    <div class="form-actions">
      <%= link_to "Back", sale_on_sales_path, :class => "btn" %>
    </div>
	 </fieldset>
</div>