config/routes.rb
Rails.application.routes.draw do
  # Add your extension routes here
  
  resources :sale_on_sales do
    collection do
      get "all"
    end
  end
  resources :sale_on_sale_imports
end

app/views/layouts/sale_on_sale.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Styletag, Sale on Sale Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <%= stylesheet_link_tag "bootstrap/bootstrap" %>
    <%= javascript_include_tag "jquery" %>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Styletag Sale On Sale</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Sale on Sale", sale_on_sales_path %></li>
              <li><%= link_to "Import", sale_on_sale_imports_path %></li>
            </ul>
            
            <p class="navbar-text pull-right">Logged in as <%= current_user.firstname %> <%= link_to t('logout'), destroy_user_session_path %></p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="span12">
      <% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %>
          <button class="close" data-dismiss="alert">×</button>
        </div>
      <% end %>
      <h2>Import file:</h2>
      <%= render "sale_on_sale_imports/form" %>
      <h2>Add a product to sale on sale:</h2>
      <%= render  "sale_on_sale_imports/new_sale_on_sale" %>
    
      <%= yield %>

      <hr>

      <footer>
        <p>&copy; Styletag 2012</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

  </body>
</html>